spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: iDoo0Hao123 # Login password of the redis server.
    port: 7000
    timeout: 0
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数
  http:
    multipart:
      enabled: true # Enable support of multi-part uploads.
      file-size-threshold: 4KB # Threshold after which files will be written to disk. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
      location: /tmp # Intermediate location of uploaded files.
      max-file-size: 5Mb # Max file size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
      max-request-size: 50Mb # Max request size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/njxzc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hodoo123
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true




server:
  port: 8080
  tomcat:
    accesslog:
      debug: true #请求响应数据调试

security:
  jwt:
    secret: k09BQnaF
    expiration: 604800 #7Days

upload:
  #Disk upload
  work-folder-name: /Users/zhangxd/files #文件存储路径
  access-url: http://127.0.0.1:8090 #文件访问地址，可使用反向代理



